apiVersion: v1
kind: Service
metadata:
  name: redis-01
  namespace: maya-decoys
spec:
  selector:
    app: redis-01
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: redis
      port: 6379
      targetPort: 6379
