#!/bin/sh
case "$1" in
  stats)
    if [ -f /var/lib/misc/.state ]; then
      cat /var/lib/misc/.state
    else
      echo '{"attackers":{},"stolen_creds":{},"active_sessions":{}}'
    fi
    ;;
  *)
    echo "Usage: $0 {stats}"
    exit 1
    ;;
esac
