apiVersion: apps/v1
kind: Deployment
metadata:
  name: jump-01
  namespace: maya-decoys
  labels:
    maya.decoy/type: jump
    maya.decoy/tier: low
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jump-01
  template:
    metadata:
      labels:
        app: jump-01
        maya.decoy/type: jump
    spec:
      runtimeClassName: gvisor
      automountServiceAccountToken: false
      containers:
        - name: jump
          image: maya-jump:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 22
              name: ssh
          env:
            - name: DECOY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jump-creds
                  key: password
            - name: MAYA_STATE_FILE
              value: /var/lib/maya/.syscache
          volumeMounts:
            - name: syscache
              mountPath: /var/lib/maya
          resources:
            requests:
              cpu: 100m
              memory: 350Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: syscache
          emptyDir: {}
